---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: rust:1.38-alpine3.10
  commands:
    - rustc main.rs
    - ./main