---
kind: pipeline
type: docker
name: default

workspace:
  base: /data/rust-tmp
  path: .

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: build
  image: rust:1.38-alpine3.10
  commands:
    - rustc main.rs
